default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: cj
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gs_development

test:
  <<: *default
  database: gs_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
